name: rapidinho
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.2
  shimmer: ^0.0.5
  google_maps_webservice: ^0.0.9
  sqflite: any
  path_provider: any
  flutter_sticky_header: ^0.3.4
  cloud_firestore: ^0.8.2+3
  google_maps_flutter:
   git:
     url: git://github.com/flutter/plugins
     path: packages/google_maps_flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/rapidinho_launcher.jpg
    - assets/images/r_red.jpg
    - assets/images/r_white.jpg
    - assets/images/rapidinho_red.jpg
    - assets/images/rapidinho_white.jpg
    - assets/images/rapidinho_cover.png
    - assets/images/rapidinho_transparent_white.png
    - assets/images/rapidinho_transparent_red.png
    - assets/images/r_transparent.png
    - assets/images/featured_meal.jpg
    - assets/images/henrick.jpg
    - assets/images/1x1_transparent.png
    - assets/images/empty_cart_state.png
    - assets/images/deliverables/books.png
    - assets/images/deliverables/drink.png
    - assets/images/deliverables/food.png
    - assets/images/deliverables/hamburger.png
    - assets/images/deliverables/ice_cream.png
    - assets/images/deliverables/letter.png
    - assets/images/deliverables/mail.png
    - assets/images/deliverables/pizza.png
    - assets/images/deliverables/present.png
    - assets/images/deliverables/wear.png
    - assets/images/deliverables/delivery_scooter.png
    - assets/images/home_items/home_item.png
    - assets/images/home_items/home_item1.jpg
    - assets/images/home_items/home_item2.png
    - assets/images/home_items/home_item3.jpg
    - assets/images/home_items/home_item4.jpg
    - assets/images/home_items/home_item5.jpg
    - assets/images/home_items/home_item6.jpg
    - assets/images/home_items/home_item7.jpg
    - assets/images/home_items/home_item8.jpg
    - assets/images/home_items/home_item9.jpg
    - assets/images/home_items/home_item10.jpg
    - assets/images/home_items/home_item11.jpg
    - assets/images/home_items/home_item12.jpg
    - assets/images/home_items/home_item13.jpg
    - assets/images/home_items/home_item14.jpg
    - assets/images/home_items/home_item15.jpeg

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani/Rajdhani-Light.ttf
        - asset: assets/fonts/Rajdhani/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani/Rajdhani-Medium.ttf
        - asset: assets/fonts/Rajdhani/Rajdhani-SemiBold.ttf
        - asset: assets/fonts/Rajdhani/Rajdhani-Bold.ttf
    - family: Fontello
      fonts:
        - asset: assets/fonts/Fontello/fontello.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
